---
- name: This is the playbook for installing httpd,copy, and restart the service
  hosts: all
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: latest
    - name: copy a file
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: restart the service
      service:
        name: apache2
        state: started
        enabled: yes
...
