---
- name: This is the playbook for installing Nginx, restart the Nginx service & copy index.html
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: latest
    - name: Restart the Nginx Service
      service:
        name: nginx
        state: started
        enabled: yes
    - name: copy a file
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html

...
